"""Reproduce every comparison and preserve reference outputs verbatim."""

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from engine.parser import parse_std
from engine.solver import solve
from engine.adapter import build_payload, make_config
from engine.comparison import compare
from engine.errors import AnalysisError


def main():
    root = Path(__file__).resolve().parents[1]
    p = argparse.ArgumentParser()
    p.add_argument("--samples", type=Path, default=root / "examples")
    p.add_argument("--strict", action="store_true")
    args = p.parse_args()
    dest = root / "validation"
    dest.mkdir(exist_ok=True)
    reports = {}
    physical_rows = []
    lines = [
        "# Reference validation results",
        "",
        "Generated by `python scripts/validate_samples.py`. Reference outputs are supplied OpenSTAAD JSON; no live STAAD run is implied.",
        "",
        "Tolerance: max(0.1% of reference, 0.01 kN / 0.01 kN-m / 0.05 mm). Full metric details, governing locations and evaluation of the reference point are in `validation/comparison.json`.",
        "",
        "| Sample | Members | Value metrics passed | Differences | Missing |",
        "|---|---:|---:|---:|---:|",
    ]
    for folder in sorted(args.samples.glob("sample*")):
        model_path = next(folder.glob("*.std"))
        flow = (
            "fully_unitized"
            if folder.name in {"sample1", "sample2", "sample3"}
            else "casement"
        )
        reference = folder / "reference.json"
        if not reference.exists():
            reference = folder / "output.txt"
        ref = (
            json.loads(reference.read_text(encoding="utf-8"))
            if reference.exists() and reference.stat().st_size
            else None
        )
        parsed = parse_std(model_path)
        try:
            solved = solve(parsed)
        except AnalysisError as error:
            report = compare(ref, {}) if ref else {"reference_available": False}
            report.update(
                analysis_status="rejected", error_code=error.code, message=str(error)
            )
            reports[folder.name] = report
            (dest / (folder.name + ".json")).write_text(
                json.dumps(report, indent=2, allow_nan=False), encoding="utf-8"
            )
            missing = report.get("counts", {}).get("missing", 0)
            lines.append(
                f"| {folder.name} | {len(parsed.members)} | Analysis rejected | — | {missing} blocked |"
            )
            physical_rows.append(
                f"| {folder.name} | Analysis rejected: {error.code} | — | — |"
            )
            print(folder.name, error.code, str(error), flush=True)
            continue
        candidate = build_payload(solved, make_config(model_path, flow))
        physical = candidate["physical_response"]
        physical_rows.append(
            f"| {folder.name} | {physical['forces']['MZ']['value']:.9f} | {physical['displacement']['absolute']['value']:.9f} | {physical['displacement']['chord_relative']['value']:.9f} |"
        )
        (dest / (folder.name + ".json")).write_text(
            json.dumps(candidate, indent=2, allow_nan=False), encoding="utf-8"
        )
        if ref:
            report = compare(ref, candidate, solved)
            report["reference_file"] = str(reference.relative_to(root)).replace(
                "\\", "/"
            )
            reports[folder.name] = report
            c = report["counts"]
            lines.append(
                f"| {folder.name} | {len(solved.elements)} | {c['pass']} | {c['difference']} | {c['missing']} |"
            )
        else:
            reports[folder.name] = {"reference_available": False}
            lines.append(
                f"| {folder.name} | {len(solved.elements)} | No supplied reference | — | — |"
            )
        print(
            folder.name, reports[folder.name].get("counts", "no reference"), flush=True
        )
    lines += ["", "## Differences requiring review", ""]
    for sample, report in reports.items():
        if report.get("analysis_status") == "rejected":
            lines.append(
                f"* **{sample}: {report['error_code']}** — {report['message']} Its supplied reference values remain unverified; they are never substituted for analysis results."
            )
            continue
        for row in report.get("metrics", []):
            if row["value_status"] != "pass":
                lines.append(
                    f"* {sample}, `{row['metric']}`: reference **{row['reference']}**, in-house **{row['candidate']}**. Absolute error **{row['absolute_difference']:.9f}**, tolerance **{row['tolerance']:.9f}**. Location assessment: `{row['location_status']}` (this does not change the failed value comparison)."
                )
    lines += [
        "",
        "## Interpretation",
        "",
        "Moment recovery finds analytical extrema, including load discontinuities. For samples 1 and 2, evaluating the solver at the supplied reference station reproduces the reference moment, while the true extremum lies between the reference stations. This is a documented semantic difference, not rounded away.",
        "",
        "Shear deformation is included using explicit AY/AZ when supplied. For PRIS with both YD and ZD but no shear areas, a Cowper rectangular coefficient times AX is used. This is an engineering assumption supported by the present force comparisons; arbitrary extrusion shear areas require independent input/validation.",
        "",
        "The compatibility adapter uses endpoint translations/rotations and an Euler-Bernoulli fixed-end load bubble for section displacement. The raw solver retains full Timoshenko translations. Remaining displacement differences and governing-source differences require an OpenSTAAD member-level oracle before claiming production interchangeability.",
        "",
        "Reference JSON contains envelopes rather than a complete member/nodal result database. Numerical equilibrium and analytical tests provide additional evidence, but cannot prove full STAAD equivalence. Sample 5 has no reference. Units for in-house stations are metres, while reference stations use inches. End-force station 0/1 is an end identifier.",
        "",
        "Sample 6 uses a separately normalized reference.json because its original output.txt lost all JSON quotes and colons. Numeric values are unchanged and the raw file is preserved. Sample 7 has an unrestrained lower assembly and is rejected pending confirmation of its intended support conditions; see SAMPLE_6_7_VALIDATION.md.",
        "",
        "See `KNOWN_LIMITATIONS.md` and `INHOUSE_SOLVER_ARCHITECTURE.md` for scope and assumptions.",
        "",
        "## Continuous physical response",
        "",
        "These additive results use all members, axial and shear deformation, both sides of point forces and couples, and roots of the piecewise field derivatives. They have different definitions from the legacy reference envelopes and are not included in the legacy comparisons. The interface defaults to these physical values; select Legacy extraction to reproduce the compatibility view.",
        "",
        "| Sample | Maximum absolute MZ (kN-m) | Absolute resultant displacement (mm) | Member chord-relative resultant (mm) |",
        "|---|---:|---:|---:|",
        *physical_rows,
        "",
        "Independent virtual-work and subdivision tests are in `tests/test_accuracy_audit.py`. Passing them establishes agreement for those beam models and tolerances, not 100% accuracy for arbitrary structures or superiority to STAAD.Pro.",
    ]
    (dest / "comparison.json").write_text(
        json.dumps(reports, indent=2, allow_nan=False), encoding="utf-8"
    )
    (root / "docs/VALIDATION_RESULTS.md").write_text(
        "\n".join(lines) + "\n", encoding="utf-8"
    )
    return (
        1
        if args.strict
        and any(
            not r.get("all_values_within_tolerance", False) for r in reports.values()
        )
        else 0
    )


if __name__ == "__main__":
    raise SystemExit(main())
