'use strict';

const $=id=>document.getElementById(id);

let selectedFile=null,completedFileName='model.std',jobId=null,result=null,model=null,busy=false,showLabels=false,yaw=0,pitch=0,zoom=1;
const number=v=>typeof v==='number'?v.toLocaleString('en-US',{minimumFractionDigits:3,maximumFractionDigits:3}):'—';

function choose(file){if(!file||busy)return;if(!file.name.toLowerCase().endsWith('.std')){failure('Choose a STAAD .std model file.');return;}selectedFile=file;$('file-label').textContent=file.name;}

$('file').addEventListener('change',e=>choose(e.target.files[0]));

for(const type of ['dragover','dragleave','drop'])$('dropzone').addEventListener(type,e=>{e.preventDefault();$('dropzone').classList.toggle('dragover',type==='dragover');if(type==='drop')choose(e.dataTransfer.files[0]);});

document.querySelectorAll('[data-example]').forEach(button=>button.addEventListener('click',async()=>{try{if(busy)return;const sample=button.dataset.example;const response=await fetch('/examples/'+sample);if(!response.ok)throw Error('Could not load example.');const file=new File([await response.blob()],sample+'.std',{type:'text/plain'});$('flow').value=button.dataset.flow;choose(file);await run();}catch(error){failure(error.message);}}));

function setBusy(value){busy=value;$('run').disabled=value;$('file').disabled=value;$('flow').disabled=value;document.querySelectorAll('[data-example]').forEach(b=>b.disabled=value);$('cancel').hidden=!value;$('request').disabled=value;}

function failure(message){$('progress-panel').hidden=false;$('progress-panel').classList.add('error');$('progress-title').textContent='Analysis could not complete';$('message').textContent=message;$('solve-time').textContent='No analysis result';if(!model)$('model-count').textContent='Model preview unavailable';$('cases').textContent='NO ANALYSIS RESULTS';setBusy(false);}

async function run(){if(busy)return;if(!selectedFile){failure('Choose a model file or one of the supplied examples.');return;}setBusy(true);result=null;model=null;jobId=null;completedFileName=selectedFile.name;$('download').disabled=true;$('empty').hidden=false;draw();for(const key of ['bm','sf','af','df']){$(key).textContent='—';$(key+'-detail').textContent='Awaiting analysis';}$('model-count').textContent='Loading model…';$('cases').textContent='AWAITING MODEL';$('solve-time').textContent='Analysis in progress';$('profiles').replaceChildren();$('progress-panel').hidden=false;$('progress-panel').classList.remove('error');$('progress-title').textContent='Analysis in progress';$('progress').value=0;$('percent').textContent='0%';$('message').textContent='Uploading model…';$('model-title').textContent=selectedFile.name;
try{const form=new FormData();form.append('std_file',selectedFile);form.append('extraction_flow',$('flow').value);if($('request').files[0])form.append('generation_request',$('request').files[0]);const response=await fetch('/jobs',{method:'POST',body:form});const body=await response.json();if(!response.ok)throw Error(body.detail?.message||JSON.stringify(body.detail)||'Upload failed.');jobId=body.job_id;await poll();}catch(error){failure(error.message);}}

$('analysis-form').addEventListener('submit',e=>{e.preventDefault();run();});

$('cancel').addEventListener('click',async()=>{if(!jobId)return;$('cancel').disabled=true;try{const response=await fetch(`/jobs/${jobId}/abort`,{method:'POST'});if(!response.ok)throw Error('Cancellation request failed.');}catch(e){$('message').textContent=e.message;}finally{$('cancel').disabled=false;}});

async function loadModelGeometry(){try{const response=await fetch(`/jobs/${jobId}/model`);if(!response.ok)return;model=await response.json();$('empty').hidden=true;zoom=1;yaw=0;pitch=0;draw();$('model-count').textContent=Object.keys(model.nodes).length+' nodes · '+Object.keys(model.members).length+' members · '+Object.keys(model.supports).length+' supports';}catch(error){$('model-count').textContent='Model preview unavailable';}}

async function poll(){while(busy){const response=await fetch(`/jobs/${jobId}`);if(!response.ok)throw Error('Could not read job status.');const state=await response.json();$('progress').value=state.progress_percent;$('percent').textContent=state.progress_percent+'%';$('message').textContent=state.message;if(state.status==='failed'){await loadModelGeometry();throw Error(state.error?.message||'Analysis failed.');}if(state.status==='canceled'){$('progress-title').textContent='Analysis canceled';$('solve-time').textContent='Canceled';$('model-count').textContent='Analysis canceled';setBusy(false);return;}if(state.status==='succeeded'){const r=await fetch(`/jobs/${jobId}/result`);if(!r.ok)throw Error('Could not retrieve analysis results.');result=await r.json();render(result.result);await loadModelGeometry();$('progress-title').textContent='Analysis complete';$('message').textContent='Results are ready. Check the validation report for the supported scope and remaining differences.';$('solve-time').textContent='Completed in '+result.duration_seconds.toFixed(2)+' s';$('download').disabled=false;setBusy(false);return;}await new Promise(resolve=>setTimeout(resolve,350));}}

function paintMetrics(data){const p=data.properties,physical=$('response-mode').value==='physical'&&data.physical_response;const values=physical?{bm:physical.forces.MZ,sf:physical.forces.FY,af:physical.forces.FX,df:physical.displacement.absolute}:{bm:p.bending_moment?.major,sf:p.shear_force?.major,af:p.axial_force,df:p.displacement};for(const[key,v]of Object.entries(values)){$(key).textContent=number(v?.value);$(key+'-detail').textContent=v?.member_id?'Member '+v.member_id+' · Load case '+v.load_case:v?.node_id?'Node '+v.node_id+' · Load case '+v.load_case:key==='af'?'No inner mullions in this group':'No value';}$('response-note').textContent=physical?'All members, including shear deformation. Continuous peaks; profile table below retains the legacy extraction definitions.':'Legacy reporting: member-end shear, classified axial force, and sampled section displacement. The exported JSON also contains the full physical response.';}
$('response-mode').addEventListener('change',()=>{if(result){paintMetrics(result.result);draw();}});
function render(data){const p=data.properties;paintMetrics(data);
$('cases').textContent='LOAD CASES '+data.analysis.load_cases.join(' / ');const body=$('profiles');body.replaceChildren();function row(name,count,metrics){const tr=document.createElement('tr');[name,count,...metrics].forEach(value=>{const td=document.createElement('td');td.textContent=value;tr.append(td);});body.append(tr);}

if(data.casement){for(const[name,g]of Object.entries(data.casement.profiles)){const signed=key=>g[key]?.min&&g[key]?.max?number(g[key].min.value)+' / '+number(g[key].max.value):'—';row(name.replaceAll('_',' '),g.member_ids.length,[signed('bm'),signed('sf'),signed('af'),signed('df')]);}$('table-note').textContent='Casement values show signed minimum / maximum. Displacement uses chord-relative member deflection and the profile’s selected nodes.';}else{const names=data.profiles?['global',...Object.keys(data.profiles.member_counts)]:['global'];for(const name of names){const g=name==='global'?p:p[name];if(!g)continue;row(name,name==='global'?(data.analysis.diagnostics?.members??'—'):data.profiles.member_counts[name],[number(g.bending_moment?.major?.value),number(g.shear_force?.major?.value),number(g.axial_force?.value),number(g.displacement?.value)]);}$('table-note').textContent='Absolute envelopes. Transom displacement follows the existing support-relative extraction rule. Empty axial results mean no inner mullions.';}}

$('download').addEventListener('click',()=>{if(!result)return;const url=URL.createObjectURL(new Blob([JSON.stringify(result,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=completedFileName.replace(/\.std$/i,'')+'-results.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>{yaw=b.dataset.view==='iso'?.55:0;pitch=b.dataset.view==='iso'?.2:0;zoom=1;document.querySelectorAll('[data-view]').forEach(v=>v.classList.toggle('selected',v===b));draw();}));

$('labels').addEventListener('click',()=>{showLabels=!showLabels;$('labels').classList.toggle('selected',showLabels);$('labels').setAttribute('aria-pressed',showLabels);draw();});

function draw(){const canvas=$('model'),rect=canvas.getBoundingClientRect(),dpr=window.devicePixelRatio||1;canvas.width=rect.width*dpr;canvas.height=rect.height*dpr;const c=canvas.getContext('2d');c.scale(dpr,dpr);if(!model)return;const entries=Object.entries(model.nodes);const project=p=>{let x=p[0]*Math.cos(yaw)+p[2]*Math.sin(yaw),z=-p[0]*Math.sin(yaw)+p[2]*Math.cos(yaw);return[x,-p[1]*Math.cos(pitch)+z*Math.sin(pitch)];};const points=entries.map(([id,p])=>project(p));const lo=[Math.min(...points.map(p=>p[0])),Math.min(...points.map(p=>p[1]))],hi=[Math.max(...points.map(p=>p[0])),Math.max(...points.map(p=>p[1]))];const scale=Math.min((rect.width-100)/Math.max(hi[0]-lo[0],.1),(rect.height-75)/Math.max(hi[1]-lo[1],.1))*zoom;const mapped={};entries.forEach(([id,p])=>{const v=project(p);mapped[id]=[(v[0]-(lo[0]+hi[0])/2)*scale+rect.width/2,(v[1]-(lo[1]+hi[1])/2)*scale+rect.height/2-6];});const governing=$('response-mode').value==='physical'?result?.result.physical_response?.forces.MZ?.member_id:result?.result.properties.bending_moment?.major?.member_id;for(const[id,m]of Object.entries(model.members)){const a=mapped[m.start],b=mapped[m.end];c.beginPath();c.moveTo(...a);c.lineTo(...b);c.strokeStyle=Number(id)===governing?'#c29248':'#53745d';c.lineWidth=Number(id)===governing?3.5:1.6;c.stroke();if(showLabels){c.font='9px Segoe UI';c.fillStyle='#80937b';c.fillText(id,(a[0]+b[0])/2+5,(a[1]+b[1])/2-4);}}for(const[id,p]of Object.entries(mapped)){c.beginPath();c.arc(...p,2.1,0,Math.PI*2);c.fillStyle='#5c7b61';c.fill();if(model.supports[id]){c.beginPath();c.moveTo(p[0],p[1]+4);c.lineTo(p[0]-4,p[1]+10);c.lineTo(p[0]+4,p[1]+10);c.closePath();c.fillStyle='#b7c89e';c.fill();}}c.font='10px Segoe UI';c.fillStyle='#96a58d';c.fillText('Y ↑',17,23);c.fillText('X →',17,38);}

let drag=null;$('model').addEventListener('pointerdown',e=>{drag=[e.clientX,e.clientY];e.target.setPointerCapture(e.pointerId);});$('model').addEventListener('pointermove',e=>{if(!drag)return;yaw+=(e.clientX-drag[0])*.008;pitch=Math.max(-1.3,Math.min(1.3,pitch+(e.clientY-drag[1])*.008));drag=[e.clientX,e.clientY];draw();});$('model').addEventListener('pointerup',()=>drag=null);$('model').addEventListener('pointercancel',()=>drag=null);$('model').addEventListener('wheel',e=>{if(!model)return;e.preventDefault();zoom=Math.max(.3,Math.min(5,zoom*Math.exp(-e.deltaY*.001)));draw();},{passive:false});new ResizeObserver(draw).observe($('model'));

fetch('/health?check=staad').then(r=>r.json()).then(data=>{$('health').textContent=data.healthy?(data.details?.backend==='inhouse'?'In-house engine ready':'OpenSTAAD ready'):'Engine unavailable';}).catch(()=>$('health').textContent='Server unavailable');

